### ISSUE TITLE
Upgrade from 3.3.0 to 3.3.2 TZ environment variable failure

### ISSUE THREAD

**Issue by vaughnmb** [jjethwa/rundeck#177]
The only way I could upgrade from 3.3.0 to 3.3.2 was to remove my TZ env var.  Originally, the TZ env var was set to 'US/Central'.  Then I changed TZ env var to 'America/Chicago' and that didn't fix it either.  The only way to get the container to stay up was to remove the TZ env var.  

Here is the error in the log file that was causing the container to restart due the TZ env var:

Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_265]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2120) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2143) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:869) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]

**Comment by jjethwa** [comment]
Hi @vaughnmb 

Looks like a similar issue to https://github.com/jjethwa/rundeck/issues/175  Can you try the solution there and let me know?

**Comment by vaughnmb** [comment]
That was it.  Thanks.
