### ISSUE TITLE
"connect timed out" for rundeck-cli 

### ISSUE THREAD

**Issue by ghost** [jjethwa/rundeck#34]
Hi guys,
i have some problems using the rundeck-cli tool. For example when i try the simple command
`rd system`
i get the following:

```
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at okhttp3.internal.Platform.connectSocket(Platform.java:126)
        at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:140)
        at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
        at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
        at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
        at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
        at okhttp3.RealCall.getResponse(RealCall.java:240)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
        at org.rundeck.client.util.FormAuthInterceptor.authenticate(FormAuthInterceptor.java:65)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:46)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.rundeck.client.util.Client.checkError(Client.java:72)
        at org.rundeck.client.tool.commands.RDSystem.info(RDSystem.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:656)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:406)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:285)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:406)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:285)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:248)
        at org.rundeck.client.tool.App.main(App.java:20)
```

Here are my settings:
profile

```
-Drundeck.jetty.connector.forwarded=true
-Dserver.web.context=/rundeck
```

framework.properties

```
framework.server.name = rundeck
framework.server.hostname = my-internal-hostname.net
framework.server.port = 4440
framework.server.url = http://my-internal-hostname.net:4440/rundeck
# Username/password used by CLI tools.
framework.server.username = admin
framework.server.password = password
```

rundeck-config.properties
`grails.serverURL=https://my-external-hostname.net/rundeck`

also i'm setting the following enviroment variables
RUNDECK_USER=admin
RUNDECK_PASSWORD=password
RUNDECK_URL=http://my-internal-hostname.net:4440/rundeck

any ideas why it is not working?

**edit:**
i fixed the timeout problem with a trailing slash in the RUNDECK_URL variable

i get another error now:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.InputStreamReader@8b96fde; line: 1, column: 2]
```

how can i find out which file is the probleme here?

**Comment by jjethwa** [comment]
Hi @ljmscx 

In https://github.com/jjethwa/rundeck/issues/33  you had Rundeck set up to use HTTPS and port 4443? 

Also, if you're still using SSL, what type of cert is it?  You might need to add the necessary chain certs to the cacerts file and set the following params in your profile

```
export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/cacerts \
-Djavax.net.ssl.trustStoreType=jks \
-Djavax.net.ssl.trustStorePassword=<CACERTS_KEYSTORE_PASSWORD>\
-Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"
```

**Comment by ljmscx** [comment]
hi @jjethwa 
i switched to http because i already have ssl on my proxy and my internal cert was self signed.

It turns out that the trailing slash was wrong. So the error is the following with debug output:
```
--> GET http://my-internal-hostname.net:4440/rundeck/api/16/system/info HTTP/1.1
<-- 403 Forbidden http://my-internal-hostname.net:4440/rundeck/api/16/system/info (59ms, unknown-length body)
--> GET http://my-internal-hostname.net:4440/rundeck/ HTTP/1.1
<-- 200 OK http://my-internal-hostname.net:4440/rundeck/user/login (19ms, unknown-length body)
--> POST http://my-internal-hostname.net:4440/rundeck/j_security_check HTTP/1.1 (43-byte body)
java.net.SocketTimeoutException: connect timed out
```

The error changed from `Unexpected character` to `connect timed out` after i removed the trailing slash from the RUNDECK_URL.

I also opened an issue on the rundeck-cli project, because i think this is not an docker container problem. But if you still have some solution suggestions i would be happy about it.

**Comment by jjethwa** [comment]
Hi @ljmscx 

Thanks!  I'll keep an eye on the issue:

https://github.com/rundeck/rundeck-cli/issues/4

Appreciate it :)

**Comment by jjethwa** [comment]
@ghost

Any updates?

**Comment by DrHashi** [comment]
Until this day, this is still not working

**Comment by jjethwa** [comment]
@DrHashi 

Are you experiencing the same issue?  I need some more details.  I have been using the new CLI utility without issue with my setup and have no issues 😞

**Comment by DrHashi** [comment]
Yes, it keeps timing out unless I use the private ip address on both the grails server definition and the rd-cli

when I try to do this using a public address for both it just flat out fails with the timeout error

**Comment by jjethwa** [comment]
Just to confirm, you're on the latest rd-cli?  https://github.com/rundeck/rundeck-cli/releases

It almost seems like it could be a routing issue with the docker daemon...

**Comment by DrHashi** [comment]
Yes I am running 1.1.1 alongside with docker since rundeck hasn't officially released a working container

**Comment by jjethwa** [comment]
Hmm, double check your docker bridge settings.  I think that might have something to do with this due to the private vs public IP.

**Comment by DrHashi** [comment]
Much appreciated, turns out docker was not able to forward the public address because it got published through all the interfaces with IPs assigned. In my case, the public IP of my instance was not set on the container.

Had to add a publish using my public ip.

docker run ... -p ${public_ip}:4440:4440

**Comment by jjethwa** [comment]
That's great news.  Thanks, @DrHashi 😄
